### ISSUE TITLE
System.InvalidOperationException: Type GenericGrain does not implement interface with id xxx

### ISSUE THREAD

**Issue by petriashev** [OrleansContrib/OrleansDashboard#260] opened 2019-10-01 10:20 UTC
See: https://github.com/dotnet/orleans/issues/4233
Problem reproduces when Orleans Dashboard is on.

**Comment by SebastianStehle** [comment] 2019-10-01 10:32
But what shall we do?

**Comment by petriashev** [comment] 2019-10-01 19:08
Maybe you know workaround or fix?

**Comment by richorama** [comment] 2019-10-01 23:09
I've not seen this error. What's the impact? 

The dashboard includes a generic grain (as we need to format the type signature) with the test grains, although this shouldn't be showing up when adding the dashboard to another project. Is this what's causing the problem?

The dashboard does of course intercept traffic to generic grains that you may have, is the problem?

**Comment by petriashev** [comment] 2019-10-02 19:36
The problem occurs when I try to use generic grain instead of specific. I can create sample with reproduce.

**Comment by richorama** [comment] 2019-10-02 20:14
A repro would be great. But if it’s a bug in orleans itself, we might not be able to do much about it here. 

Happy to have a go though. :-)

**Comment by ReubenBond** [comment] 2019-10-02 20:30
I have a repro for this in Orleans (see the linked issue). I'll attempt to fix this today

**Comment by petriashev** [comment] 2019-10-02 20:45
[OrleansBug4233.zip](https://github.com/OrleansContrib/OrleansDashboard/files/3683236/OrleansBug4233.zip)

**Comment by petriashev** [comment] 2019-10-02 20:46
In SiloHost:
// Uncomment and you will get exception in TestClientHostedService.StartAsync (https://github.com/dotnet/orleans/issues/4233)
//.UseDashboard()

**Comment by SebastianStehle** [comment] 2019-10-02 21:03
The problem is not the dashboard itself but any feature that make use of `IIncomingGrainCallFilter`. Going to close this issue here as we cannot do anything.

**Closed by SebastianStehle** 2019-10-02 21:03 UTC
