### ISSUE TITLE
Getting `no messages recorded` when looking at custom grain. 

### ISSUE THREAD

**Issue by Ulriksen** [OrleansContrib/OrleansDashboard#275] opened 2019-11-20 09:06 UTC
System grains got data, but dashboard will not show data for cusom grain. The grain url in the dashboard starts with a `.` example `/#/grain/.Program.Progress`

Here's a complete code example to reproduce the problem can be found here https://github.com/Ulriksen/fnconf/blob/master/Program.fs

**Comment by richorama** [comment] 2019-11-20 09:09
Thanks for the repro, I'll look at this in the next couple of days.

**Comment by Ulriksen** [comment] 2019-11-20 09:11
I've tried adding namespace and module to the code, the grain id is now `FnConf.Demo.Progress` but still no data recorded.

**Comment by richorama** [comment] 2019-11-20 23:23
Hi @Ulriksen, I have managed to get the code running (I only needed to update the storage connection string). However (as far as I can tell) it doesn't seem to call any grains. My F# skills are extremely primitive, would you be able to alter the sample to build a client and made some calls to a grain? Thank you!

**Comment by Ulriksen** [comment] 2019-11-21 07:27
Sorry, forgot to write about that connection string. Once it is running Kestrel will run on ports 5000 (HTTP) and 5001 (HTTPS). You can call it on http://localhost:5000/progress/someUser/someEpisode/12345 to set a "position" of 12345. Giraffe will route this (routef with three parameters, %s is string and %i is integer). This will call the grain and write to the storage. You can then open http://localhost:5000/progress/someUser/someEpisode to read the position from the grain.

**Comment by richorama** [comment] 2019-11-22 02:11
Thank you @Ulriksen, this is fixed in 3.0.7

I found the cause, the dashboard code that intercepts the grain call to record the profiling information gets the name of the grain type using `type.FullName`.

When Orleans returns grain statistics it uses an internal method called `GetFullName` to apply additional formatting to this type name.

https://github.com/dotnet/orleans/blob/b279a53197a0de2926eb9fae312bc9e66cd117e1/src/Orleans.Core/CodeGeneration/TypeUtils.cs#L311-L326

(you could argue the bug is in here!).

My solution for now is to use the same `GetFullName` method in the dashboard, so the grain types will now match correctly, and the dashboard can correlate the grain stats and profile data.

Thank you for your repro, I wouldn't have found the bug without it :¬)

**Closed** 2019-11-22 02:11 UTC
